spring:
  application:
    name: task-manager
  profiles:
    active: dev

  # Datasource Configuration
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: username
    password: password

  # JPA Configuration

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# App Information
app:
  name: Task Manager
  version: 1.0.0
  max-task-per-page: 20

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logger,beans,mappings
      base-path: /actuator

    health:
      show-details: always

    info:
      env:
        enabled: true

  info:
    app:
      description: a simple task management application built with spring boot
      version: 1.0.0
      author: alvinskylers