spring.application.name=task-manager

# H2 DATABASE CONFIGURATION

#database connection string url
spring.datasource.url=jdbc:h2:mem:taskdb

#database connection driver
spring.datasource.driverClassName= org.h2.Driver

#database connection username
spring.datasource.username=username

#database connection password
spring.datasource.password=password


# JPA CONFIGURATION

# spring boot versions < 3 require to specify the database dialect to allow communication with the database
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring boot automatically generates or changes the tables in the database based on the entity classes
spring.jpa.hibernate.ddl-auto=update

# spring boot shows SQL queries on the terminal while it's running
spring.jpa.show-sql=true


# H2 CONFIGURATION
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
